# 1. Import

In [55]:
import sys
from pathlib import Path

# Add project root to path to import config
project_root = Path().resolve().parent
sys.path.insert(0, str(project_root))

import pandas as pd
from config.config import BASE_DIR

# Define relative paths to data files
afp_path = BASE_DIR / "data" / "raw" / "afp" / "data.json"
fakenewsnet_path = BASE_DIR / "data" / "raw" / "fakenewsnet" / "data.json"
france24_path = BASE_DIR / "data" / "raw" / "france24" / "data.json"
google_factcheck_path = BASE_DIR / "data" / "raw" / "google_fact_check" / "data.json"

# Load datasets
df_afp = pd.read_json(afp_path)
df_fakenewsnet = pd.read_json(fakenewsnet_path)
df_france24  = pd.read_json(france24_path)
df_gfc = pd.read_json(google_factcheck_path)

# 2. Exploration

## 2.1 AFP

In [56]:
df_afp.head()

,id,source,title,date,url,label,main_image,content_blocks
0,afp_642e028d,AFP Factuel,"Non, un laboratoire n'a pas établi de lien ent...",2026-02-23 10:56:39+01:00,https://factuel.afp.com/doc.afp.com.98BR7KE,Faux,https://factuel.afp.com/sites/default/files/me...,"[{'type': 'paragraphe', 'content': 'Arrivée en..."
1,afp_6e2acf07,AFP Factuel,Affaire Epstein : comment la désinformation pr...,2026-02-18 19:11:54+01:00,https://factuel.afp.com/doc.afp.com.972M7CU,Faux,https://factuel.afp.com/sites/default/files/me...,"[{'type': 'paragraphe', 'content': 'Un puits s..."
2,afp_8eb6d940,AFP Factuel,"Cannibalisme, ""rituels sataniques"" : gare à ce...",2026-02-25 12:00:52+01:00,https://factuel.afp.com/doc.afp.com.986M8NQ,Faux,https://factuel.afp.com/sites/default/files/me...,"[{'type': 'paragraphe', 'content': 'Le 30 janv..."
3,afp_b09d7712,AFP Factuel,Municipales en France: la crainte d'ingérences...,2026-02-03 12:28:20+01:00,https://factuel.afp.com/doc.afp.com.94KA4G3,Faux,https://factuel.afp.com/sites/default/files/me...,"[{'type': 'paragraphe', 'content': 'Si aucune ..."
4,afp_1be69019,AFP Factuel,Attention à cette fausse vidéo d'un porte-avio...,2026-03-02 20:13:58+01:00,https://factuel.afp.com/doc.afp.com.99L69G3,Faux,https://factuel.afp.com/sites/default/files/me...,"[{'type': 'paragraphe', 'content': 'Fin févrie..."

In [57]:
df_afp.describe(include='all')

,id,source,title,date,url,label,main_image,content_blocks
count,52,52,52,52,52,52,52,52
unique,52,1,52,NaN,52,1,52,52
top,afp_642e028d,AFP Factuel,"Non, un laboratoire n'a pas établi de lien ent...",NaN,https://factuel.afp.com/doc.afp.com.98BR7KE,Faux,https://factuel.afp.com/sites/default/files/me...,"[{'type': 'paragraphe', 'content': 'Arrivée en..."
freq,1,52,1,NaN,1,52,1,1
mean,NaN,NaN,NaN,2026-02-06 13:08:25.557692+01:00,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,2026-01-14 12:31:06+01:00,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,2026-01-25 23:24:44.250000+01:00,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,2026-02-05 06:07:29.500000+01:00,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,2026-02-18 12:19:56.250000+01:00,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,2026-03-02 20:13:58+01:00,NaN,NaN,NaN,NaN

In [58]:
(df_afp.isna().sum() / df_fakenewsnet.shape[0])*100

id                0.0
source            0.0
title             0.0
date              0.0
url               0.0
label             0.0
main_image        0.0
content_blocks    0.0
dtype: float64

---

## 2.2 FakeNewsNet

In [59]:
df_fakenewsnet.head()

,id,source,title,date,url,label,main_image,content_blocks
0,Fake_1-Webpage,FakeNewsNet,Proof The Mainstream Media Is Manipulating The...,2016-09-19 00:00:00,http://www.addictinginfo.org/2016/09/19/proof-...,Faux,http://addictinginfo.addictinginfoent.netdna-c...,"[{'type': 'paragraphe', 'content': 'I woke up ..."
1,Fake_10-Webpage,FakeNewsNet,Charity: Clinton Foundation Distributed “Water...,2016-09-21 00:08:41,http://eaglerising.com/36899/charity-clinton-f...,Faux,http://eaglerising.com/wp-content/uploads/2016...,"[{'type': 'paragraphe', 'content': 'Former Pre..."
2,Fake_11-Webpage,FakeNewsNet,A Hillary Clinton Administration May be Entire...,2016-09-21 00:10:38,http://eaglerising.com/36880/a-hillary-clinton...,Faux,http://eaglerising.com/wp-content/uploads/2016...,"[{'type': 'paragraphe', 'content': 'After coll..."
3,Fake_12-Webpage,FakeNewsNet,Trump’s Latest Campaign Promise May Be His Mos...,2016-09-19 00:00:00,http://www.addictinginfo.org/2016/09/19/trumps...,Faux,http://addictinginfo.addictinginfoent.netdna-c...,"[{'type': 'paragraphe', 'content': 'Donald Tru..."
4,Fake_13-Webpage,FakeNewsNet,Website is Down For Maintenance,NaT,http://www.proudcons.com/clinton-foundation-ca...,Faux,NaN,"[{'type': 'paragraphe', 'content': 'Website is..."

In [62]:
df_fakenewsnet.loc[0]

id                                                   Fake_1-Webpage
source                                                  FakeNewsNet
title             Proof The Mainstream Media Is Manipulating The...
date                                            2016-09-19 00:00:00
url               http://www.addictinginfo.org/2016/09/19/proof-...
label                                                          Faux
main_image        http://addictinginfo.addictinginfoent.netdna-c...
content_blocks    [{'type': 'paragraphe', 'content': 'I woke up ...
Name: 0, dtype: object

In [ ]:
df_fakenewsnet.describe(include='all')

,id,source,title,date,url,label,main_image,content_blocks
count,410,410,410,295,410,410,408,410
unique,203,1,280,NaN,287,2,271,281
top,Real_1-Webpage,FakeNewsNet,NFL Superstar Unleashes 4 Word Bombshell on Re...,NaN,http://occupydemocrats.com/2016/09/28/trump-sa...,Vrai,http://conservativetribune.com/wp-content/uplo...,"[{'type': 'paragraphe', 'content': 'McCain Cri..."
freq,3,410,7,NaN,4,209,7,7
mean,NaN,NaN,NaN,2016-09-18 16:59:39.969491,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,2015-04-22 15:10:33,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,2016-09-20 03:04:55.500000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,2016-09-22 08:29:08,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,2016-09-26 06:35:18,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,2017-08-24 09:21:00,NaN,NaN,NaN,NaN

In [ ]:
(df_fakenewsnet.isna().sum() / df_fakenewsnet.shape[0])*100

id                 0.000000
source             0.000000
title              0.000000
date              28.048780
url                0.000000
label              0.000000
main_image         0.487805
content_blocks     0.000000
dtype: float64

---

## 2.3 france24

In [ ]:
df_france24.head()

,id,source,title,date,url,label,main_image,content_blocks
0,F24_a67eee65,France_24,"Tunisie : autour de Sfax, la pression pour le ...",NaT,https://www.france24.com/fr/%C3%A9missions/les...,Faux,https://s.france24.com/media/display/042e5f06-...,[]
1,F24_8d267e48,France_24,"Ukraine : les ""mines papillons"" visent les civils",NaT,https://www.france24.com/fr/%C3%A9missions/les...,Faux,https://s.france24.com/media/display/4499efa8-...,[]
2,F24_b91c14a8,France_24,Ukraine : comment les drones russes harcèlent ...,2026-02-21 05:40:16+00:00,https://www.france24.com/fr/%C3%A9missions/les...,Faux,https://s.france24.com/media/display/146fed50-...,"[{'type': 'paragraphe', 'content': 'Dans le su..."
3,F24_909c4812,France_24,Yémen : dans les prisons secrètes de Hadramout,2026-02-20 20:59:45+00:00,https://www.france24.com/fr/%C3%A9missions/les...,Faux,https://s.france24.com/media/display/fbef7c06-...,"[{'type': 'paragraphe', 'content': 'Sous forte..."
4,F24_25fda911,France_24,"Au Venezuela, un journaliste sorti de prison b...",2026-02-04 18:37:30+00:00,https://www.france24.com/fr/%C3%A9missions/les...,Faux,https://s.france24.com/media/display/9f4d2cc8-...,"[{'type': 'paragraphe', 'content': 'Dans cette..."

In [ ]:
df_france24.describe(include="all")

,id,source,title,date,url,label,main_image,content_blocks
count,21,21,21,15,21,21,21,21
unique,21,1,21,NaN,21,1,21,16
top,F24_a67eee65,France_24,"Tunisie : autour de Sfax, la pression pour le ...",NaN,https://www.france24.com/fr/%C3%A9missions/les...,Faux,https://s.france24.com/media/display/042e5f06-...,[]
freq,1,21,1,NaN,1,21,1,6
mean,NaN,NaN,NaN,2026-01-02 16:15:07.133333+00:00,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,2025-11-11 14:23:33+00:00,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,2025-12-10 15:54:47+00:00,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,2025-12-24 11:46:21+00:00,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,2026-01-31 02:49:22+00:00,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,2026-02-21 05:40:16+00:00,NaN,NaN,NaN,NaN

In [ ]:
(df_france24.isna().sum() / df_france24.shape[0])*100

id                 0.000000
source             0.000000
title              0.000000
date              28.571429
url                0.000000
label              0.000000
main_image         0.000000
content_blocks     0.000000
dtype: float64

---

## 2.4 google_factcheck

In [ ]:
df_gfc.head()

,id,source,title,date,url,label,main_image,content_blocks
0,gfc_db30d8e7,google_fact_check,"VÉRIF' - Le ""logo de la Jeune Garde"" était-il ...",2026-02-19 17:56:39+00:00,https://www.tf1info.fr/politique/verif-le-logo...,Faux,NaN,"[{'type': 'paragraphe', 'content': 'Le logo de..."
1,gfc_d33a86b7,google_fact_check,VÉRIF' - L'assistant parlementaire de Raphaël ...,2026-02-19 14:56:28+00:00,https://www.tf1info.fr/politique/verif-l-assis...,Plutôt faux,NaN,"[{'type': 'paragraphe', 'content': 'L'assistan..."
2,gfc_8441909f,google_fact_check,VÉRIF' - Le pape a-t-il vraiment refusé de rec...,2026-01-21 18:28:08+00:00,https://www.tf1info.fr/politique/verif-le-pape...,Faux,NaN,"[{'type': 'paragraphe', 'content': 'Le pape a ..."
3,gfc_285f4869,google_fact_check,"VÉRIF' - Est-il vrai que la ""plupart des dirig...",2026-01-15 18:19:08+00:00,https://www.tf1info.fr/politique/verif-est-il-...,Faux,NaN,"[{'type': 'paragraphe', 'content': 'La plupart..."
4,gfc_df36089c,google_fact_check,"VÉRIF' - ""Labellisation des médias"" : le vrai ...",2025-12-05 09:00:55+00:00,https://www.tf1info.fr/politique/verif-labelli...,Faux,NaN,"[{'type': 'paragraphe', 'content': 'Emmanuel M..."

In [ ]:
df_gfc.describe(include='all')

,id,source,title,date,url,label,main_image,content_blocks
count,687,687,687,686,687,687,0.0,687
unique,687,1,684,NaN,687,168,NaN,685
top,gfc_db30d8e7,google_fact_check,"Covid-19 : Après le vaccin, des caillots mutan...",NaN,https://www.tf1info.fr/politique/verif-le-logo...,Faux,NaN,"[{'type': 'paragraphe', 'content': 'Aucun part..."
freq,1,687,2,NaN,1,316,NaN,2
mean,NaN,NaN,NaN,2022-03-11 09:31:14.877551+00:00,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,2016-09-16 08:11:53+00:00,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,2021-03-11 15:55:15+00:00,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,2021-09-28 17:18:00+00:00,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,2023-01-29 06:24:45+00:00,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,2026-02-19 17:56:39+00:00,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
(df_gfc.isna().sum() / df_gfc.shape[0])*100

id                  0.00000
source              0.00000
title               0.00000
date                0.14556
url                 0.00000
label               0.00000
main_image        100.00000
content_blocks      0.00000
dtype: float64

---